{{- if default "" .Values.externalUrl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ## 增加副本数配置
  replicas: 1
  ## 增加标签匹配，以下三行代码
  selector:
    matchLabels:
      app: {{ template "gitlab-ce.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab-ce.fullname" . }}
    spec:
      containers:
      - name: {{ template "gitlab-ce.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.

        ## 增加GITLAB_SECRETS_DB_KEY_BASE、GITLAB_SECRETS_SECRET_KEY_BASE、GITLAB_SECRETS_OTP_KEY_BASE变量配置
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string
          
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        ## DB configuration
        ##增加GITLAB_NOTIFY_ON_BROKEN_BUILDS， GITLAB_NOTIFY_PUSHER，GITLAB_BACKUP_SCHEDULE，GITLAB_BACKUP_TIME，DB_TYPE变量配置
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00
        - name: DB_TYPE
          value: postgres

        - name: DB_HOST
          value: {{ template "gitlab-ce.postgresql.fullname" . }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-password
        - name: DB_DATABASE
          value: {{ .Values.postgresql.postgresDatabase | quote }}
        ## Redis configuration
        - name: REDIS_HOST
          value: {{ template "gitlab-ce.redis.fullname" . }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: redis-password
        ports:
          - name: ssh
            containerPort: 22
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        ## 提取探针到values文件，统一配置
        {{- toYaml .Values.probe | nindent 8 }}
        ## 优化资源
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - name: gitlab-etc
            mountPath: /etc/gitlab
          - name: gitlab-data
            mountPath: /gitlab-data
      volumes:
      - name: gitlab-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-data
      {{- if .Values.persistence.gitlabData.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ else }}
{{ end }}