global:
  edition: ce
  hosts:
    domain: edgecraft.acornsoft.io # ingress 도메인 설정 / 앞에 gitlab이 알아서 붙음
    gitlab:
      name: gitlab.edgecraft.acornsoft.io
      https: true
    registry:
      name: registry.edgecraft.acornsoft.io
      https: true
    minio:
      name: minio.edgecraft.acornsoft.io
      https: true
  ingress:
    configureCertmanager: false
    # gitlab-nginx 클래스로 설정되어 있을 건데 ingress-nginx-controller를 사용할 예정이므로 nginx 클래스로 변경한다.
    class: "nginx"
    tls:
      enabled: true

certmanager: # 공인 IP, 도메인이 없어 cert-manager 컴포넌트 미사용
  install: false

# gitlab nginx-ingress 컴포넌트 미사용
# 준비사항에서 설치한 쿠버네티스 ingress를 이용함
nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false
