apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: harbor
spec:
  clusterSelector:
    matchLabels:
      harborChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: harbor
  version: 1.12.2
  namespace: harbor
  #releaseName: harbor
  options:
    disableHooks: true
    # skipCRDs: false
    # subNodes: fasle
    # disableOpenAPIValidation: false
    atomic: true
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
      # includeCRDs: true
    upgrade:
      #   force: false
      resetValues: true
    #   reuseValues: false
    #   maxHistory: 10
    #   cleanupOnFail: true
    # uninstall:
    #   keepHistory: false
    #   description: ""
  valuesTemplate: |
    expose:
      type: nodePort
