apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: jupyterhub
spec:
  clusterSelector:
    matchLabels:
      jupyterhubChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: jupyterhub
  version: 2.0.0
  namespace: jupyterhub
  releaseName: jupyterhub
  options:
    #   disableHooks: true
    #   skipCRDs: false
    #   subNodes: fasle
    #   disableOpenAPIValidation: false
    #   atomic: true
    waitForJobs: true
    wait: true
    #   timeout: 5m
    install:
      createNamespace: true
    #     includeCRDs: true
    upgrade:
      #     force: false
      #     resetValues: true
      #     reuseValues: false
      #     maxHistory: 10
      cleanupOnFail: true
  #   uninstall:
  #     keepHistory: false
  #     description: ""
  valuesTemplate: |
    hub:
      networkPolicy:
        interNamespaceAccessLabels: accept
    proxy:
      secretToken: 2a454a47ad547ac9549cd462e08289d3a6d5a5d39498339be6016fde522cb713
      service:
        type: NodePort
        nodePorts:
          http: 32560
          https: 32561
    ingress:
      enabled: false
    singleuser:
      cpu:
        limit: 1
        guarantee: 0.5
      memory:
        limit: 2G
        guarantee: 1G
      serviceAccountName: spark
      startTimeout: 600
      defaultUrl: "/lab"
      cloudMetadata:
        blockWithIptables: false
      storage:
        homeMountPath: /home/{username}
      image:
        name: jupyter/pyspark-notebook
        tag: latest
        pullPolicy: IfNotPresent
        pullSecrets: []
      cmd: ["/usr/local/bin/start-singleuser.sh"]
    cull:
      enabled: false
    debug:
      enabled: true
