apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: gitlab
spec:
  clusterSelector:
    matchLabels:
      gitlabChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: gitlab
  version: 7.1.1
  namespace: gitlab
  releaseName: gitlab
  options:
    #   disableHooks: true
    #   skipCRDs: false
    #   subNodes: fasle
    #   disableOpenAPIValidation: false
    #   atomic: true
    waitForJobs: true
    wait: true
    #   timeout: 5m
    install:
      createNamespace: true
    #     includeCRDs: true
    upgrade:
      #     force: false
      #     resetValues: true
      #     reuseValues: false
      #     maxHistory: 10
      cleanupOnFail: true
  #   uninstall:
  #     keepHistory: false
  #     description: ""
  valuesTemplate: |
    global:
      edition: ce
      hosts:
        domain: edgecraft.acornsoft.io
        gitlab:
          name: gitlab.edgecraft.acornsoft.io
          https: true
        registry:
          name: registry.edgecraft.acornsoft.io
          https: true
        minio:
          name: minio.edgecraft.acornsoft.io
          https: true
      ingress:
        configureCertmanager: false
        class: nginx
        tls:
          enabled: true
    certmanager-issuer:
      email: ccambo@acornsoft.io
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
    registry:
      enabled: false
