apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: jaeger
spec:
  clusterSelector:
    matchLabels:
      jaegerChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: jaeger
  version: 0.71.11
  namespace: jaeger
  releaseName: jaeger
  options:
    # disableHooks: true
    # skipCRDs: false
    # subNodes: fasle
    # disableOpenAPIValidation: false
    # atomic: true
    waitForJobs: true
    wait: true
    dependencyUpdate: true
    timeout: 5m
    install:
      createNamespace: true
      # includeCRDs: true
    # upgrade:
    #   force: false
    #   resetValues: true
    #   reuseValues: false
    #   maxHistory: 10
    #   cleanupOnFail: true
    # uninstall:
    #   keepHistory: false
    #   description: ""
  valuesTemplate: |
    provisionDataStorage:
      cassandra: false
    storage:
      type: elasticsearch
      elasticsearch:
        host: elasticsearch-master.efk
        password: "1234"
    query:
      service:
        type: NodePort
        nodePort: 32500
