apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ingress-nginx
spec:
  clusterSelector:
    matchLabels:
      ingressnginxChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: ingress-nginx
  version: v4.7.1
  namespace: ingress-nginx
  #releaseName: ingress-nginx
  options:
    disableHooks: true
    # skipCRDs: false
    # subNodes: fasle
    # disableOpenAPIValidation: false
    atomic: true
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
      includeCRDs: true
    upgrade:
      #   force: false
      resetValues: true
    #   reuseValues: false
    #   maxHistory: 10
    #   cleanupOnFail: true
    # uninstall:
    #   keepHistory: false
    #   description: ""
  valuesTemplate: |
    controller:
      admissionWebhooks:
        certmanager:
          enabled: true
      metrics:
        enabled: true
      service:
        type: NodePort
        nodePorts:
          http: 30001
          https: 30002
    tcp:
      22: gitlab/gitlab-gitlab:22
