apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: spark-operator
spec:
  clusterSelector:
    matchLabels:
      sparkoperatorChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: spark-operator
  version: 1.1.27
  namespace: spark-operator
  releaseName: spark-operator
  options:
    #   disableHooks: true
    #   skipCRDs: false
    #   subNodes: fasle
    #   disableOpenAPIValidation: false
    #   atomic: true
    waitForJobs: true
    wait: true
    #   timeout: 5m
    install:
      createNamespace: true
    #     includeCRDs: true
    upgrade:
      #     force: false
      #     resetValues: true
      #     reuseValues: false
      #     maxHistory: 10
      cleanupOnFail: true
  #   uninstall:
  #     keepHistory: false
  #     description: ""
  valuesTemplate: |
    replicaCount: 1
    image:
      repository: ghcr.io/googlecloudplatform/spark-operator
      pullPolicy: IfNotPresent
      tag: ""
    imagePullSecrets: []
    # 별도의 미리 생성한 네임스페이스에서 Job을 분리해서 실행할 경우 지정.
    #sparkJobNamespace: "spark-work"
