apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: csi-driver-nfs
spec:
  clusterSelector:
    matchLabels:
      csiNfsChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts/stable
  chartName: csi-driver-nfs
  namespace: kube-system
  valuesTemplate: |
    nfs:
      server: 192.168.88.11
      path: /data/hdd/nfs-storage
