apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argocd
spec:
  clusterSelector:
    matchLabels:
      argocdChart: enabled
  repoURL: https://acornsoft-edgecraft.github.io/edgecraft-caaph/helm-charts
  chartName: argo-cd
  version: 5.43.4
  namespace: argocd
  releaseName: argocd
  options:
    #   disableHooks: true
    #   skipCRDs: false
    #   subNodes: fasle
    #   disableOpenAPIValidation: false
    #   atomic: true
    waitForJobs: true
    wait: true
    #   timeout: 5m
    install:
      createNamespace: true
    #     includeCRDs: true
    upgrade:
      #     force: false
      #     resetValues: true
      #     reuseValues: false
      #     maxHistory: 10
      cleanupOnFail: true
  #   uninstall:
  #     keepHistory: false
  #     description: ""
  valuesTemplate: |
    server:
      service:
        type: NodePort
        nodePortHttp: 32570
        nodePortHttps: 32571
