apiVersion: v1
appVersion: 9.4.1
deprecated: false
description: GitLab Community Edition
home: https://about.gitlab.com
keywords:
  - git
  - ci
  - deploy
  - issue tracker
  - code review
  - wiki
name: gitlab-ce
sources:
  - https://hub.docker.com/r/gitlab/gitlab-ce/
  - https://docs.gitlab.com/omnibus/
version: 0.2.3
